### ISSUE TITLE
The filters don't work anymore

### ISSUE THREAD

**Issue by antoinecourtin** [hashmich/DHCR-Front-End#3]
Hello, 
I have the impression that the filters don't work anymore.
When I filter on "Art and cultural studies", I get a message "Error while loading data"

**Comment by hashmich** [comment]
Many thanks Antoine. 
We know already and are working to find what is causing this. There have been big structural changes behind the scenes recently, possibly it is related with that.

**Comment by hashmich** [comment]
Fixing an API-related bug has solved this issue.
